/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package logindatabase;

import java.sql.*;
import javax.swing.*;

/**
 * class that create the MainWindow
 * @author Alexandre
 * @version 11.2
 */
public class MainWindow extends javax.swing.JFrame {
Connection conn=null;
PreparedStatement pst=null;
ResultSet rs=null;
    /**
     * Creates new form Menu
     */
    public MainWindow() {
        initComponents();
    }

     /**
     * Creates new form MainWindow with the database information
     * @version 1.1
     * @param username  username of the person connected to the database
     * @param password  password of the person connected to the database
     */
    public MainWindow(String username, String password){
        this.password = password;
        this.username = username;
        initComponents();
            
    }
    
    /**
     * fonction that return the password of the logged person
     * @return the password
     */
    public String getPassword(){
        return this.password;
    }
    
    /**
     * fonction that return the username of the logged person
     * @return the username
     */
    public String getUsername(){
        return this.username;
    }
    
    /**
     * fonction that return the id number of a technicien
     * @return the id number
     */
    public int getID(){
        conn = UserDao.ConnectDB();
        String Sql="Select ID from utilisateur where (LOGIN=? and PASSWORD=?)";
        int id = 0;
         try{
            pst=conn.prepareStatement(Sql);
            pst.setString(1,this.username);
            pst.setString(2,this.password);
            rs=pst.executeQuery();
            while (rs.next()){
                id = rs.getInt("ID");
            }
            pst.close();
            
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null,e);
            
        }
        return id;
    }
    
    public String getNom(){
        
        conn = UserDao.ConnectDB();
        String str = "";
         String Sql="Select nom from technicien where (id = ?)";
         try{
            pst=conn.prepareStatement(Sql);
            pst.setString(1,Integer.toString(getID()));
            rs=pst.executeQuery();
            while (rs.next()){
                str = rs.getString("nom");
            }
            pst.close();
            
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null,e);
            
        }
        return str;
    }
    
    public String getPrenom(){
        
        conn = UserDao.ConnectDB();
        String str = "";
        String Sql="Select prenom from technicien where (id = ?)";
         try{
            pst=conn.prepareStatement(Sql);
            pst.setString(1,Integer.toString(getID()));
            rs=pst.executeQuery();
            while (rs.next()){
                str = rs.getString("prenom");
            }
            pst.close();
            
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null,e);
            
        }
        return str;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConnect = new javax.swing.JButton();
        btnDisconnect = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnProfile = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnListeTaches = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnConnect.setText("Connect");
        btnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectActionPerformed(evt);
            }
        });

        btnDisconnect.setText("Disconnect");
        btnDisconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisconnectActionPerformed(evt);
            }
        });

        jLabel1.setText("Connected Technician :");

        btnProfile.setText("Profile");
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(254, 124, 2));
        btnExit.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnListeTaches.setText("Task List");
        btnListeTaches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListeTachesActionPerformed(evt);
            }
        });

        jLabel3.setText(this.getUsername());
        jLabel3.revalidate();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(btnListeTaches, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnConnect, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDisconnect, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConnect)
                    .addComponent(btnDisconnect)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProfile)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addComponent(btnListeTaches, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
        LoginWindow l=new LoginWindow();
        l.setVisible(true);
    }//GEN-LAST:event_btnConnectActionPerformed

    private void btnDisconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisconnectActionPerformed
        // TODO add your handling code here:
        if (this.username != null){
            this.username =null;
            this.password =null;
            setVisible(false);
            dispose();   
            MainWindow m=new MainWindow();
            m.setVisible(true);
        }
        else{
              JOptionPane.showMessageDialog(null,"can't disconnect","Not connected",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDisconnectActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        // TODO add your handling code here:
        if (this.username != null && this.password != null){ 
            setVisible(false);
            dispose();
            ProfileWindow p = new ProfileWindow(username, password);
            p.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null,"can't see profile","Not connected",JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_btnProfileActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnListeTachesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListeTachesActionPerformed
        // TODO add your handling code here:
        if (this.username == null || this.password == null){
            JOptionPane.showMessageDialog(null,"can't show tasks","Not connected",JOptionPane.ERROR_MESSAGE);
        }
        else {
            ActivitiesWindow a = new ActivitiesWindow(username, password, this.getID());
            a.setVisible(true);
            this.setVisible(false);
            dispose();
        }    
    }//GEN-LAST:event_btnListeTachesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    private String username;
    private String password;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConnect;
    private javax.swing.JButton btnDisconnect;
    private javax.swing.JButton btnExit;
    private javax.swing.JToggleButton btnListeTaches;
    private javax.swing.JButton btnProfile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
